spring:
  application:
    name: dashboard-service

  datasource:
    url: jdbc:h2:mem:dashboarddb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true

  h2:
    console:
      enabled: true
      path: /h2-console

---
spring:
  config:
    activate:
      on-profile: test
  sql:
    init:
      mode: never
